from shared.exception.base import BaseAppException


class NotFound(BaseAppException):
    pass
